/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20PresetMinterPauser } from "./ERC20PresetMinterPauser";
export * as factories from "./factories";
export { ERC20PresetMinterPauser__factory } from "./factories/ERC20PresetMinterPauser__factory";
